### ISSUE TITLE
error running Network-Status-Page

### ISSUE THREAD

**Issue by duramato** [rohankapoorcom/Network-Status-Page#1]
While tring to run it from run.py im getting this error,dont know why...

Traceback (most recent call last):
  File "run.py", line 39, in <module>
    main()
  File "run.py", line 18, in main
    config = json.load(config_file)
  File "/usr/lib/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 19 column 26 (char 438)
Exception KeyError: KeyError(3067295260L,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
suergonkas@suergonkas-PC:~/netstatus$ Exception KeyError: KeyError(3067295260L,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
-bash: erro de sintaxe próximo do `token' não esperado`('

**Comment by duramato** [comment]
Any Clue?
